version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo "Fase de build começando.."
      - mvn clean install
  post-build:
    commands:
      - echo "Pipeline sucesso"
